### ISSUE TITLE
我们能给你赞助吗？

### ISSUE THREAD

**Issue by wssbqyy2** [html5syt/kill-mythware#1]
如题

**Comment by html5syt** [comment]
额，这么说吧，这个项目是我很早在Github上建立的，目的只是为了收集网上的极域杀手等类似软件，现在早已不再维护，但是还是感谢您的支持～(￣▽￣～)~

**Comment by html5syt** [comment]
额，这么说吧，这个项目是我很早在Github上建立的，目的只是为了收集网上的极域杀手等类似软件，现在早已不再维护，但是还是感谢您的支持～(￣▽￣～)~
